name: Deploy Wedding Site

on:
  repository_dispatch:
    types: [deploy_wedding_trigger] # Tên sự kiện chúng ta tự đặt

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Template Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.template_branch }} # Lấy nhánh theme tương ứng

      - name: Install Dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          # Bơm ID đám cưới vào quá trình Build
          NEXT_PUBLIC_WEDDING_ID: ${{ github.event.client_payload.wedding_id }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      - name: Deploy Project Artifacts to Vercel
        # Deploy lệnh này sẽ tạo ra 1 URL riêng
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Print URL
        run: cat deployment-url.txt
